### ISSUE TITLE
Potenzieller Bug: curly braces expected, trotz korrekter Methodenform

### ISSUE THREAD

**Issue by leMineGaming** [martin-pabst/Online-IDE-new-compiler#1]
Keine Ahnung warum der Fehler auftritt...
`public class Knoten {
    private string key;
    public boolean besucht;
 
    public Knoten(string key) {
       this.key = key;
    }
 
    public string GetKey() {
       return key;
    }
 }
 
 public class Graph {
    int[][] adjazenzmatrix;
    int knotenAnzahl = 0;
    Knoten[] knotenFeld;
    ArrayList<Knoten> warteschlange;
    
    public Graph(int maxKnoten) {
       knotenFeld = new Knoten[maxKnoten];
       adjazenzmatrix = new int[maxKnoten][maxKnoten];
       matrixGenerieren();
       initTest();
    }
 
    public boolean isNeighbourFrom(Knoten k1, Knoten k2) {
       if(adjazenzmatrix[getIndex(k1.GetKey())][getIndex(k2.GetKey())] != -1) {
          return true;
       }
       else{
          return false;
       }
    }
 
    public Knoten breitenSuche(string startknoten, string gesuchterknoten) {
       Knoten stK = knotenFeld[getIndex(startknoten)];
       stK.besucht = true;
       warteschlange.add(stK);
 
       for (int i = 0; i < knotenFeld.length; i++) {
          if(isNeighbourFrom(stK, knotenFeld[i])) {
             
          }
       }
 
    }
 
    public void initTest() {
       knotenHinzufügen("CSG");
       knotenHinzufügen("ZOB");
       knotenHinzufügen("Valentin");
       knotenHinzufügen("Dominik");
 
       kantenHinzufügen("CSG", "ZOB", 7);
       kantenHinzufügen("ZOB", "Valentin", 13);
       kantenHinzufügen("Valentin", "CSG", 18);
       kantenHinzufügen("Valentin", "Dominik", 20);
       kantenHinzufügen("Dominik", "CSG", 15);
    }
 
    public void kantenHinzufügen(string startkey, string endkey, int weight) {
       int startindex = getIndex(startkey);
       int endindex = getIndex(endkey);
 
       if(startindex > -1 && endindex > -1) {
          adjazenzmatrix[startindex][endindex] = weight;
          adjazenzmatrix[endindex][startindex] = weight;
       }
    }
 
    public int getIndex(string knotenschlüssel) {
       for (int i = 0; i < knotenFeld.length; i++) {
          if(knotenFeld[i].GetKey().equalsIgnoreCase(knotenschlüssel)) {
             return i;
          }
       }
       return -1;
    }
 
    public void knotenHinzufügen(string newkey) {
       Knoten newKnoten = new Knoten(newkey);
       knotenFeld[knotenAnzahl] = newKnoten;
       knotenAnzahl++;
    }
 
    public void matrixGenerieren() {
       for (int x = 0; x < adjazenzmatrix.length; x++) {
          for (int y = 0; y < adjazenzmatrix.length; y++) {
             adjazenzmatrix[x][y] = -1;
          }
       }
       for (int i = 0; i < adjazenzmatrix.length; i++) {
          adjazenzmatrix[i][i] = 0;
       }
    }
 
    public void matrixAusgeben() {
       for (int x = 0; x < adjazenzmatrix.length; x++) {
          print("|", Color.gray);
          for (int y = 0; y < adjazenzmatrix.length; y++) {
             if(adjazenzmatrix[x][y] == -1) {
                print(adjazenzmatrix[x][y], Color.red);
             }
             else if(adjazenzmatrix[x][y] < 10) {
                if(adjazenzmatrix[x][y] == 0) {
                   print(" -", Color.gray);
                }
                else{
                   print(" " + adjazenzmatrix[x][y], Color.lime);
                }
                
             }
             else if(adjazenzmatrix[x][y] < 15) {
                print(adjazenzmatrix[x][y], Color.yellow);
             }
             else{
                print(adjazenzmatrix[x][y], Color.orange);
             }
             print("|", Color.gray);
             
          }
          print("\n");
       }
    }
 }
 
 Graph grp = new Graph(20);
 grp.matrixAusgeben(); `
 
 
![grafik](https://github.com/user-attachments/assets/96f2a95a-ab8c-46e5-94e9-46a82f9036b4)

**Comment by martin-pabst** [comment]
The first error in your sourcecode is at line 2 (String is uppercase!), followed by several others. By the time the compiler gets to line 27 it passed several errors and just can't make any sense of what it's seeing...
Replace all occurrencies of `string` with `String` (uppercase!), then the error in line 27 disappears.
