### ISSUE TITLE
online-id is unresponsive when the script has errors

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#10]
When there is an error in the current script, I suspect the online-ide re-tries to compile multiple times a second(?)

At least what I observe, especially noticeable when the browser dev tools are open: The online-ide then becomes unresponsive, and the devtools keep flickering.

**Comment by martin-pabst** [comment]
Thank you!
The compiler runs every 500 ms (`JavaCompiler.maxMsBetweenRuns`) and checks if any file got dirty since the last run. This check failed.
