### ISSUE TITLE
Step Over: Steps nicht konsequent gehighlightet & werden z. T. übersprungen

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#2]
Ein Programm wie

 ```java
int i = 42;
```
... benötigt 3 "Step Over"-Schritte:
1. Programm starten
2. o. g. Anweisung ausführen
3. Programm beenden

Soweit nachvollziehbar.

Ein Programm wie

```java
println(new Vector2(0, 1).plus(new Vector2(1, 0)));
```

Benötigt 4 Schritte. Probleme:
* Es müssten 6 Schritte sein: Start, new Vector2, new Vector2, plus, println, Ende.
* vor Schritt 2 erscheint einen Pfeil vor "plus"; was aber ist mit zweimal "new Vector2" - wird das übersprungen?
* vor Schritt 3 erscheint gar kein Pfeil - hier müsste "println" markiert werden (?)

**Comment by martin-pabst** [comment]
Ich habe das Problem gerade mit IntelliJ Idea nachgestellt. Es führt beim Klick auf "Step over" die komplette Anweisung
```java
println(new Vector2(0, 1).plus(new Vector2(1, 0)));
```
in einem Schritt aus. Geht man die Anweisung mit "Step Into" durch, so geht es in die Ausführung der Methode `plus` rein, nicht aber in die Konstruktoren, selbst wenn diese als Quellcode vorliegen.

Gegen einen Stop vor den Konstruktoren spricht, dass die in der Online-IDE ausgeführten Programme umso langsamer werden, je stärker sie in Steps untergliedert sind. Irgendwie ist es aber auch Geschmackssache, wie kleinschrittig innerhalb eines Terms gesteppt wird.

Dass vor Schritt 3 (println) kein Dreieck erschien lag daran, dass das Statement am Zeilenanfang steht. Dadurch wurde vermieden, dass beim schrittweisen Durchlaufen des Programms die Zeilen einzeln immer um ein Zeichen ein- und dann wieder ausrücken. Ich habe das jetzt geändert, bin mir aber nicht sicher, welche Lösung besser ist.
