### ISSUE TITLE
 node src/development/spritesheetgenerator.js : DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#30]
(node:23392) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Online-IDE-new-compiler/src/development/spritesheetgenerator.js:64
        throw err;
        ^

**Comment by martin-pabst** [comment]
If i click on "Run and debug", then "Generate Spritesheet", then the script is executed without error. 
I can't reproduce the error-message and I can't find any reference to the ''punycode"-module. 
How did you start the script?

**Comment by fjf2002** [comment]
Yes, me neither.
I tried node v20, v22, v23.

**Comment by fjf2002** [comment]
You refer to your .vscode/launch.json, which is not part of this repo.

**Comment by martin-pabst** [comment]
Done!
