### ISSUE TITLE
svgencoder fail

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#34]
old output:

```
background-image: url("data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encodi
```

output now:
```
background-image: url('data:image/svg+xml,%3C%3Fxml version="1.0" encoding="UTF-8" standalone=
```

No escaping occurs.

**Comment by fjf2002** [comment]
@martin-pabst : what does svgencoder do, is it still neccessary?

**Comment by martin-pabst** [comment]
svgencoder.ts is compiled to svgencoder.js with npm-script "build_tools". 
svgencoder takes svg-icons inside /assets/icons, converts them to data-urls and builds css-classes which it writes into file icons.css.

The new format (without escaping) miraculously works.

Close this issue?

**Comment by fjf2002** [comment]
I think we can close this issue if
1) it works and
2) it is spec compliant

**Comment by fjf2002** [comment]
@martin-pabst: Are you sure this is spec compliant?

**Comment by martin-pabst** [comment]
I realized that vite can do what svgencoder was for and now got rid of it altogether, see commit "get rid of svgencoder".
