### ISSUE TITLE
spritesheetgenerator broken?

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#35]
I suppose the spritesheetgenerator is broken ~~for a long time~~?

~~I mean, the path `../graphics/` does not exist.~~

EDIT: spritesheetgenerator references files in `./material`, which are excluded by .gitignore.

**Comment by martin-pabst** [comment]
This path is correct nevertheless. It works this way:
At runtime you can open a page with a preview of all sprites. You can test it by running `npm run dev` and then opening `http://localhost:3000/spriteLibrary.html` in your browser.
This page includes file assets/css/imagesprites.css. Therein you find links to '../graphics/spritesheet.png' which corretly link the image file at runtime.

**Comment by fjf2002** [comment]
spritesheetgenerator references files in `./material`, which are excluded by .gitignore.

**Comment by fjf2002** [comment]
Ive talked some shit Here, but I repeat my Last Claim:

> spritesheetgenerator references files in ./material, which are excluded by .gitignore

**Comment by martin-pabst** [comment]
I moved the files from ./material to ./assets/graphics/spritesheet-files and tested spritesheetgenerator.js successfully.

Close this issue?

**Comment by fjf2002** [comment]
./assets are part of the application at runtime, aren't they? That's not neccessary. I think ./material would fit better, don't you think?

**Comment by martin-pabst** [comment]
You're right. But i got used to put all files into ./material that i don't want to publish...
My suggestion: Move contents of ./material to new folder ./intern, then move ./assets/graphics/spritesheet-files and ./assets/icons to ./material.
OK?

**Comment by fjf2002** [comment]
OK
