### ISSUE TITLE
"foo".toString(); fail

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#4]
The following program

```java
"foo".toString();
```

... fails with Runtime Error
```
SystemException in thread main thread: System exception: TypeError: "foo"._mj$toString$String$ is not a function
at $MainClass553.$main (File Neue Datei.java: 1)
Execution time: 30.1 ms, 0 steps, 0 steps/s
```

* The `toString` method seems to be missing?
* Such problems could/should be checked at compile time, as usual in ordinary Java.

**Comment by martin-pabst** [comment]
Pull request has been merged. -> Thank you!
