### ISSUE TITLE
Adding Files: should be named differently

### ISSUE THREAD

**Issue by fjf2002** [martin-pabst/Online-IDE-new-compiler#5]
Add two files.
Both will be called "Neue Datei.java".
Shouldn't naming be differently? Will it result in problems, for example, them overriding each other?

Suggestion: Append ascending integers.

**Comment by martin-pabst** [comment]
As files in the online-ide may contain several class definitiions it is not required for their names to correspond to the classes' identifiers. Therefore filenames are not evaluated and it's no problem if two files have the same name.
Nevertheless it's a good idea to set default names with ascending integers. => Fixed.
